baseurl = "https://zaky.my.id"
disqusShortname = "muhammad-zaky-zulfiqor"
googleAnalytics = "UA-107358475-1"
languageCode = "en-us"
paginate = 3
pluralizeListTitles = false
preserveTaxonomyNames = true
theme = "hugo-future-imperfect"
title = "Muhammad Zaky Zulfiqor"
[[menu.main]]
identifier = "fa fa-home"
name = "Home"
url = "/"
weight = 1
[[menu.main]]
identifier = "fa fa-id-card-o"
name = "Who Am I"
url = "/about/"
weight = 2
[[menu.main]]
identifier = "fa fa-newspaper-o"
name = "Article"
url = "/article/"
weight = 3
[[menu.main]]
identifier = "fa fa-envelope-o"
name = "Contact Me"
url = "/contact/"
weight = 6
[params]
categoriesByCount = true
customCSS = ["default"]
customJS = ["default"]
description = "All about me. - Muhammad Zaky Zulfiqor"
dynamicTitles = true
faviconVersion = ""
includeReadingTime = true
loadFavicon = true
navbarTitle = "Muhammad Zaky Zulfiqor"
rssAppearAtBottom = true
rssAppearAtTop = true
socialAppearAtBottom = true
socialAppearAtTop = true
socialShare = true
viewMorePostLink = "/article/"
[params.intro]
about = "I just simple person who like photography, videography, code, and cyber security enthusiast."
header = "Muhammad Zaky Zulfiqor"
paragraph = "ムハマド・ザキ・ズルフィコル"
[params.intro.pic]
alt = "Muhammad Zaky Zulfiqor"
circle = true
imperfect = true
src = "https://raw.githubusercontent.com/zakybstrd21215/site/master/static/uploads/2019/05/10/59192853_1167859120054853_5511657369756499968_n.jpg"
width = "150"
[params.postAmount]
sidebar = 5
[params.staticman]
branch = ""
repo = ""
staticman = false
username = ""
[params.staticman.recaptcha]
secret = "ENCRYPTED_SECRET"
sitekey = "SITE_KEY"
[social]
behance = ""
bitbucket = ""
codepen = ""
deviantart = ""
dribbble = ""
email = "zaky@errorcybernews.com"
facebook = "zaky.doktrin"
flickr = "149234463@N08/albums"
foursquare = ""
github = "zakybstrd21215"
gitlab = ""
googleplus = ""
instagram = "zakybstrd21215"
jsfiddle = ""
linkedin = ""
medium = ""
pinterest = ""
qq = ""
quora = ""
reddit = ""
skype = ""
slideshare = ""
snapchat = ""
stackoverflow = ""
telegram = "zakybstrd21215"
tumblr = ""
twitter = "zakybstrd21215"
vimeo = ""
vine = ""
wechat = ""
whatsapp = "6288229041713"
wordpress = ""
xing = ""
youtube = "channel/UCRQI9LBaReBPsPqSu95UUmg?sub_confirmation=1"
